-- Enum value 'compute_similarity_scores' is added at API startup (before migrations)
-- because ALTER TYPE ... ADD VALUE cannot run inside a transaction block.
-- This file is intentionally empty to keep migration numbering consistent.
