-- Phase 1 Step 3: Make app_id/category_id NOT NULL, add FK constraints,
-- drop old slug FK columns, and rebuild indexes.

-- === Make new columns NOT NULL ===
ALTER TABLE app_snapshots ALTER COLUMN app_id SET NOT NULL;
ALTER TABLE app_field_changes ALTER COLUMN app_id SET NOT NULL;
ALTER TABLE app_category_rankings ALTER COLUMN app_id SET NOT NULL;
ALTER TABLE app_keyword_rankings ALTER COLUMN app_id SET NOT NULL;
ALTER TABLE keyword_ad_sightings ALTER COLUMN app_id SET NOT NULL;
ALTER TABLE category_ad_sightings ALTER COLUMN app_id SET NOT NULL;
ALTER TABLE category_ad_sightings ALTER COLUMN category_id SET NOT NULL;
ALTER TABLE reviews ALTER COLUMN app_id SET NOT NULL;
ALTER TABLE featured_app_sightings ALTER COLUMN app_id SET NOT NULL;
ALTER TABLE similar_app_sightings ALTER COLUMN app_id SET NOT NULL;
ALTER TABLE similar_app_sightings ALTER COLUMN similar_app_id SET NOT NULL;
ALTER TABLE app_similarity_scores ALTER COLUMN app_id_a SET NOT NULL;
ALTER TABLE app_similarity_scores ALTER COLUMN app_id_b SET NOT NULL;
ALTER TABLE app_review_metrics ALTER COLUMN app_id SET NOT NULL;
ALTER TABLE app_power_scores ALTER COLUMN app_id SET NOT NULL;
ALTER TABLE app_visibility_scores ALTER COLUMN tracked_app_id SET NOT NULL;
ALTER TABLE app_visibility_scores ALTER COLUMN app_id SET NOT NULL;
ALTER TABLE account_tracked_apps ALTER COLUMN app_id SET NOT NULL;
ALTER TABLE account_tracked_keywords ALTER COLUMN tracked_app_id SET NOT NULL;
ALTER TABLE account_competitor_apps ALTER COLUMN tracked_app_id SET NOT NULL;
ALTER TABLE account_competitor_apps ALTER COLUMN competitor_app_id SET NOT NULL;
ALTER TABLE research_project_competitors ALTER COLUMN app_id SET NOT NULL;
ALTER TABLE category_snapshots ALTER COLUMN category_id SET NOT NULL;
ALTER TABLE account_starred_categories ALTER COLUMN category_id SET NOT NULL;

-- === Add FK constraints on new id columns (safe re-run) ===
DO $$ BEGIN ALTER TABLE app_snapshots ADD CONSTRAINT fk_app_snapshots_app_id FOREIGN KEY (app_id) REFERENCES apps(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE app_field_changes ADD CONSTRAINT fk_app_field_changes_app_id FOREIGN KEY (app_id) REFERENCES apps(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE app_category_rankings ADD CONSTRAINT fk_app_category_rankings_app_id FOREIGN KEY (app_id) REFERENCES apps(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE app_keyword_rankings ADD CONSTRAINT fk_app_keyword_rankings_app_id FOREIGN KEY (app_id) REFERENCES apps(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE keyword_ad_sightings ADD CONSTRAINT fk_keyword_ad_sightings_app_id FOREIGN KEY (app_id) REFERENCES apps(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE category_ad_sightings ADD CONSTRAINT fk_category_ad_sightings_app_id FOREIGN KEY (app_id) REFERENCES apps(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE category_ad_sightings ADD CONSTRAINT fk_category_ad_sightings_category_id FOREIGN KEY (category_id) REFERENCES categories(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE reviews ADD CONSTRAINT fk_reviews_app_id FOREIGN KEY (app_id) REFERENCES apps(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE featured_app_sightings ADD CONSTRAINT fk_featured_app_sightings_app_id FOREIGN KEY (app_id) REFERENCES apps(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE similar_app_sightings ADD CONSTRAINT fk_similar_app_sightings_app_id FOREIGN KEY (app_id) REFERENCES apps(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE similar_app_sightings ADD CONSTRAINT fk_similar_app_sightings_similar_app_id FOREIGN KEY (similar_app_id) REFERENCES apps(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE app_similarity_scores ADD CONSTRAINT fk_app_similarity_scores_app_id_a FOREIGN KEY (app_id_a) REFERENCES apps(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE app_similarity_scores ADD CONSTRAINT fk_app_similarity_scores_app_id_b FOREIGN KEY (app_id_b) REFERENCES apps(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE app_review_metrics ADD CONSTRAINT fk_app_review_metrics_app_id FOREIGN KEY (app_id) REFERENCES apps(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE app_power_scores ADD CONSTRAINT fk_app_power_scores_app_id FOREIGN KEY (app_id) REFERENCES apps(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE app_visibility_scores ADD CONSTRAINT fk_app_visibility_scores_tracked_app_id FOREIGN KEY (tracked_app_id) REFERENCES apps(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE app_visibility_scores ADD CONSTRAINT fk_app_visibility_scores_app_id FOREIGN KEY (app_id) REFERENCES apps(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE account_tracked_apps ADD CONSTRAINT fk_account_tracked_apps_app_id FOREIGN KEY (app_id) REFERENCES apps(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE account_tracked_keywords ADD CONSTRAINT fk_account_tracked_keywords_tracked_app_id FOREIGN KEY (tracked_app_id) REFERENCES apps(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE account_competitor_apps ADD CONSTRAINT fk_account_competitor_apps_tracked_app_id FOREIGN KEY (tracked_app_id) REFERENCES apps(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE account_competitor_apps ADD CONSTRAINT fk_account_competitor_apps_competitor_app_id FOREIGN KEY (competitor_app_id) REFERENCES apps(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE research_project_competitors ADD CONSTRAINT fk_research_project_competitors_app_id FOREIGN KEY (app_id) REFERENCES apps(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE category_snapshots ADD CONSTRAINT fk_category_snapshots_category_id FOREIGN KEY (category_id) REFERENCES categories(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE account_starred_categories ADD CONSTRAINT fk_account_starred_categories_category_id FOREIGN KEY (category_id) REFERENCES categories(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- === Drop old slug-based indexes ===
DROP INDEX IF EXISTS idx_app_snapshots_slug_date;
DROP INDEX IF EXISTS idx_app_field_changes_slug;
DROP INDEX IF EXISTS idx_app_cat_rank;
DROP INDEX IF EXISTS idx_app_kw_rank;
DROP INDEX IF EXISTS idx_kw_ad_sightings_app_date;
DROP INDEX IF EXISTS idx_kw_ad_sightings_unique;
DROP INDEX IF EXISTS idx_cat_ad_sightings_cat_date;
DROP INDEX IF EXISTS idx_cat_ad_sightings_app_date;
DROP INDEX IF EXISTS idx_cat_ad_sightings_unique;
DROP INDEX IF EXISTS idx_reviews_dedup;
DROP INDEX IF EXISTS idx_reviews_app_date;
DROP INDEX IF EXISTS idx_featured_app_date;
DROP INDEX IF EXISTS idx_featured_unique;
DROP INDEX IF EXISTS idx_similar_sightings_app_date;
DROP INDEX IF EXISTS idx_similar_sightings_similar_date;
DROP INDEX IF EXISTS idx_similar_sightings_unique;
DROP INDEX IF EXISTS idx_app_similarity_scores_unique;
DROP INDEX IF EXISTS idx_app_similarity_scores_a;
DROP INDEX IF EXISTS idx_app_similarity_scores_b;
DROP INDEX IF EXISTS idx_app_review_metrics_unique;
DROP INDEX IF EXISTS idx_app_power_unique;
DROP INDEX IF EXISTS idx_app_power_app_date;
DROP INDEX IF EXISTS idx_app_power_cat_date_score;
DROP INDEX IF EXISTS idx_app_visibility_unique;
DROP INDEX IF EXISTS idx_app_visibility_app_date;
DROP INDEX IF EXISTS idx_app_visibility_account_tracked;
DROP INDEX IF EXISTS idx_account_tracked_apps_unique;
DROP INDEX IF EXISTS idx_account_tracked_keywords_unique;
DROP INDEX IF EXISTS idx_account_competitor_apps_unique;
DROP INDEX IF EXISTS idx_account_starred_categories_unique;
DROP INDEX IF EXISTS idx_research_project_competitors_unique;
DROP INDEX IF EXISTS idx_category_snapshots_slug_date;

-- === Create new id-based indexes ===
CREATE INDEX IF NOT EXISTS idx_app_snapshots_app_id_date ON app_snapshots (app_id, scraped_at);
CREATE INDEX IF NOT EXISTS idx_app_field_changes_app_id ON app_field_changes (app_id, detected_at);
CREATE INDEX IF NOT EXISTS idx_app_cat_rank_id ON app_category_rankings (app_id, category_slug, scraped_at);
CREATE INDEX IF NOT EXISTS idx_app_kw_rank_id ON app_keyword_rankings (app_id, keyword_id, scraped_at);
CREATE INDEX IF NOT EXISTS idx_kw_ad_sightings_app_id_date ON keyword_ad_sightings (app_id, seen_date);
CREATE UNIQUE INDEX IF NOT EXISTS idx_kw_ad_sightings_unique_id ON keyword_ad_sightings (app_id, keyword_id, seen_date);
CREATE INDEX IF NOT EXISTS idx_cat_ad_sightings_cat_id_date ON category_ad_sightings (category_id, seen_date);
CREATE INDEX IF NOT EXISTS idx_cat_ad_sightings_app_id_date ON category_ad_sightings (app_id, seen_date);
CREATE UNIQUE INDEX IF NOT EXISTS idx_cat_ad_sightings_unique_id ON category_ad_sightings (app_id, category_id, seen_date);
CREATE UNIQUE INDEX IF NOT EXISTS idx_reviews_dedup ON reviews (app_id, reviewer_name);
CREATE INDEX IF NOT EXISTS idx_reviews_app_id_date ON reviews (app_id, review_date);
CREATE INDEX IF NOT EXISTS idx_featured_app_id_date ON featured_app_sightings (app_id, seen_date);
CREATE UNIQUE INDEX IF NOT EXISTS idx_featured_unique_id ON featured_app_sightings (app_id, section_handle, surface_detail, seen_date);
CREATE INDEX IF NOT EXISTS idx_similar_sightings_app_id_date ON similar_app_sightings (app_id, seen_date);
CREATE INDEX IF NOT EXISTS idx_similar_sightings_similar_id_date ON similar_app_sightings (similar_app_id, seen_date);
CREATE UNIQUE INDEX IF NOT EXISTS idx_similar_sightings_unique_id ON similar_app_sightings (app_id, similar_app_id, seen_date);
CREATE UNIQUE INDEX IF NOT EXISTS idx_app_similarity_scores_unique_id ON app_similarity_scores (app_id_a, app_id_b);
CREATE INDEX IF NOT EXISTS idx_app_similarity_scores_a_id ON app_similarity_scores (app_id_a);
CREATE INDEX IF NOT EXISTS idx_app_similarity_scores_b_id ON app_similarity_scores (app_id_b);
CREATE UNIQUE INDEX IF NOT EXISTS idx_app_review_metrics_unique_id ON app_review_metrics (app_id, computed_at);
CREATE INDEX IF NOT EXISTS idx_app_review_metrics_date ON app_review_metrics (computed_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_app_power_unique_id ON app_power_scores (app_id, category_slug, computed_at);
CREATE INDEX IF NOT EXISTS idx_app_power_app_id_date ON app_power_scores (app_id, computed_at);
CREATE INDEX IF NOT EXISTS idx_app_power_cat_date_score ON app_power_scores (category_slug, computed_at, power_score);
CREATE UNIQUE INDEX IF NOT EXISTS idx_app_visibility_unique_id ON app_visibility_scores (account_id, tracked_app_id, app_id, computed_at);
CREATE INDEX IF NOT EXISTS idx_app_visibility_app_id_date ON app_visibility_scores (app_id, computed_at);
CREATE INDEX IF NOT EXISTS idx_app_visibility_account_tracked_id ON app_visibility_scores (account_id, tracked_app_id, computed_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_account_tracked_apps_unique_id ON account_tracked_apps (account_id, app_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_account_tracked_keywords_unique_id ON account_tracked_keywords (account_id, tracked_app_id, keyword_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_account_competitor_apps_unique_id ON account_competitor_apps (account_id, tracked_app_id, competitor_app_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_account_starred_categories_unique_id ON account_starred_categories (account_id, category_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_research_project_competitors_unique_id ON research_project_competitors (research_project_id, app_id);
CREATE INDEX IF NOT EXISTS idx_category_snapshots_cat_id_date ON category_snapshots (category_id, scraped_at);

-- === Drop old slug FK columns ===
-- First drop the FK constraints
ALTER TABLE app_snapshots DROP CONSTRAINT IF EXISTS app_snapshots_app_slug_apps_slug_fk;
ALTER TABLE app_field_changes DROP CONSTRAINT IF EXISTS app_field_changes_app_slug_apps_slug_fk;
ALTER TABLE app_category_rankings DROP CONSTRAINT IF EXISTS app_category_rankings_app_slug_apps_slug_fk;
ALTER TABLE app_keyword_rankings DROP CONSTRAINT IF EXISTS app_keyword_rankings_app_slug_apps_slug_fk;
ALTER TABLE keyword_ad_sightings DROP CONSTRAINT IF EXISTS keyword_ad_sightings_app_slug_apps_slug_fk;
ALTER TABLE category_ad_sightings DROP CONSTRAINT IF EXISTS category_ad_sightings_app_slug_apps_slug_fk;
ALTER TABLE category_ad_sightings DROP CONSTRAINT IF EXISTS category_ad_sightings_category_slug_categories_slug_fk;
ALTER TABLE reviews DROP CONSTRAINT IF EXISTS reviews_app_slug_apps_slug_fk;
ALTER TABLE featured_app_sightings DROP CONSTRAINT IF EXISTS featured_app_sightings_app_slug_apps_slug_fk;
ALTER TABLE similar_app_sightings DROP CONSTRAINT IF EXISTS similar_app_sightings_app_slug_apps_slug_fk;
ALTER TABLE similar_app_sightings DROP CONSTRAINT IF EXISTS similar_app_sightings_similar_app_slug_apps_slug_fk;
ALTER TABLE app_similarity_scores DROP CONSTRAINT IF EXISTS app_similarity_scores_app_slug_a_apps_slug_fk;
ALTER TABLE app_similarity_scores DROP CONSTRAINT IF EXISTS app_similarity_scores_app_slug_b_apps_slug_fk;
ALTER TABLE app_review_metrics DROP CONSTRAINT IF EXISTS app_review_metrics_app_slug_apps_slug_fk;
ALTER TABLE app_power_scores DROP CONSTRAINT IF EXISTS app_power_scores_app_slug_apps_slug_fk;
ALTER TABLE app_visibility_scores DROP CONSTRAINT IF EXISTS app_visibility_scores_tracked_app_slug_apps_slug_fk;
ALTER TABLE app_visibility_scores DROP CONSTRAINT IF EXISTS app_visibility_scores_app_slug_apps_slug_fk;
ALTER TABLE account_tracked_apps DROP CONSTRAINT IF EXISTS account_tracked_apps_app_slug_apps_slug_fk;
ALTER TABLE account_tracked_keywords DROP CONSTRAINT IF EXISTS account_tracked_keywords_tracked_app_slug_apps_slug_fk;
ALTER TABLE account_competitor_apps DROP CONSTRAINT IF EXISTS account_competitor_apps_tracked_app_slug_apps_slug_fk;
ALTER TABLE account_competitor_apps DROP CONSTRAINT IF EXISTS account_competitor_apps_app_slug_apps_slug_fk;
ALTER TABLE research_project_competitors DROP CONSTRAINT IF EXISTS research_project_competitors_app_slug_apps_slug_fk;
ALTER TABLE category_snapshots DROP CONSTRAINT IF EXISTS category_snapshots_category_slug_categories_slug_fk;
ALTER TABLE account_starred_categories DROP CONSTRAINT IF EXISTS account_starred_categories_category_slug_categories_slug_fk;

-- Now drop the old slug columns
ALTER TABLE app_snapshots DROP COLUMN IF EXISTS app_slug;
ALTER TABLE app_field_changes DROP COLUMN IF EXISTS app_slug;
ALTER TABLE app_category_rankings DROP COLUMN IF EXISTS app_slug;
ALTER TABLE app_keyword_rankings DROP COLUMN IF EXISTS app_slug;
ALTER TABLE keyword_ad_sightings DROP COLUMN IF EXISTS app_slug;
ALTER TABLE category_ad_sightings DROP COLUMN IF EXISTS app_slug;
ALTER TABLE category_ad_sightings DROP COLUMN IF EXISTS category_slug;
ALTER TABLE reviews DROP COLUMN IF EXISTS app_slug;
ALTER TABLE featured_app_sightings DROP COLUMN IF EXISTS app_slug;
ALTER TABLE similar_app_sightings DROP COLUMN IF EXISTS app_slug;
ALTER TABLE similar_app_sightings DROP COLUMN IF EXISTS similar_app_slug;
ALTER TABLE app_similarity_scores DROP COLUMN IF EXISTS app_slug_a;
ALTER TABLE app_similarity_scores DROP COLUMN IF EXISTS app_slug_b;
ALTER TABLE app_review_metrics DROP COLUMN IF EXISTS app_slug;
ALTER TABLE app_power_scores DROP COLUMN IF EXISTS app_slug;
ALTER TABLE app_visibility_scores DROP COLUMN IF EXISTS tracked_app_slug;
ALTER TABLE app_visibility_scores DROP COLUMN IF EXISTS app_slug;
ALTER TABLE account_tracked_apps DROP COLUMN IF EXISTS app_slug;
ALTER TABLE account_tracked_keywords DROP COLUMN IF EXISTS tracked_app_slug;
ALTER TABLE account_competitor_apps DROP COLUMN IF EXISTS tracked_app_slug;
ALTER TABLE account_competitor_apps DROP COLUMN IF EXISTS app_slug;
ALTER TABLE research_project_competitors DROP COLUMN IF EXISTS app_slug;
ALTER TABLE category_snapshots DROP COLUMN IF EXISTS category_slug;
ALTER TABLE account_starred_categories DROP COLUMN IF EXISTS category_slug;
