-- Seed Zoho Marketplace categories (flat, one per Zoho product)
INSERT INTO categories (platform, slug, title, url, category_level, parent_slug)
VALUES
  ('zoho', 'crm', 'Zoho CRM', 'https://marketplace.zoho.com/app/crm', 0, NULL),
  ('zoho', 'salesiq', 'Zoho SalesIQ', 'https://marketplace.zoho.com/app/salesiq', 0, NULL),
  ('zoho', 'desk', 'Zoho Desk', 'https://marketplace.zoho.com/app/desk', 0, NULL),
  ('zoho', 'assist', 'Zoho Assist', 'https://marketplace.zoho.com/app/assist', 0, NULL),
  ('zoho', 'meeting', 'Zoho Meeting', 'https://marketplace.zoho.com/app/meeting', 0, NULL),
  ('zoho', 'cliq', 'Zoho Cliq', 'https://marketplace.zoho.com/app/cliq', 0, NULL),
  ('zoho', 'connect', 'Zoho Connect', 'https://marketplace.zoho.com/app/connect', 0, NULL),
  ('zoho', 'recruit', 'Zoho Recruit', 'https://marketplace.zoho.com/app/recruit', 0, NULL),
  ('zoho', 'people', 'Zoho People', 'https://marketplace.zoho.com/app/people', 0, NULL),
  ('zoho', 'commerce', 'Zoho Commerce', 'https://marketplace.zoho.com/app/commerce', 0, NULL),
  ('zoho', 'campaigns', 'Zoho Campaigns', 'https://marketplace.zoho.com/app/campaigns', 0, NULL),
  ('zoho', 'sites', 'Zoho Sites', 'https://marketplace.zoho.com/app/sites', 0, NULL),
  ('zoho', 'landingpage', 'Zoho LandingPage', 'https://marketplace.zoho.com/app/landingpage', 0, NULL),
  ('zoho', 'invoice', 'Zoho Invoice', 'https://marketplace.zoho.com/app/invoice', 0, NULL),
  ('zoho', 'books', 'Zoho Books', 'https://marketplace.zoho.com/app/books', 0, NULL),
  ('zoho', 'inventory', 'Zoho Inventory', 'https://marketplace.zoho.com/app/inventory', 0, NULL),
  ('zoho', 'billing', 'Zoho Billing', 'https://marketplace.zoho.com/app/billing', 0, NULL),
  ('zoho', 'expense', 'Zoho Expense', 'https://marketplace.zoho.com/app/expense', 0, NULL),
  ('zoho', 'checkout', 'Zoho Checkout', 'https://marketplace.zoho.com/app/checkout', 0, NULL),
  ('zoho', 'workdrive', 'Zoho WorkDrive', 'https://marketplace.zoho.com/app/workdrive', 0, NULL),
  ('zoho', 'zeptomail', 'Zoho ZeptoMail', 'https://marketplace.zoho.com/app/zeptomail', 0, NULL),
  ('zoho', 'teaminbox', 'Zoho TeamInbox', 'https://marketplace.zoho.com/app/teaminbox', 0, NULL),
  ('zoho', 'writer', 'Zoho Writer', 'https://marketplace.zoho.com/app/writer', 0, NULL),
  ('zoho', 'show', 'Zoho Show', 'https://marketplace.zoho.com/app/show', 0, NULL),
  ('zoho', 'mail', 'Zoho Mail', 'https://marketplace.zoho.com/app/mail', 0, NULL),
  ('zoho', 'analytics', 'Zoho Analytics', 'https://marketplace.zoho.com/app/analytics', 0, NULL),
  ('zoho', 'sprints', 'Zoho Sprints', 'https://marketplace.zoho.com/app/sprints', 0, NULL),
  ('zoho', 'bugtracker', 'Zoho BugTracker', 'https://marketplace.zoho.com/app/bugtracker', 0, NULL),
  ('zoho', 'projects', 'Zoho Projects', 'https://marketplace.zoho.com/app/projects', 0, NULL),
  ('zoho', 'orchestly', 'Zoho Orchestly', 'https://marketplace.zoho.com/app/orchestly', 0, NULL),
  ('zoho', 'creator', 'Zoho Creator', 'https://marketplace.zoho.com/app/creator', 0, NULL)
ON CONFLICT (platform, slug) DO UPDATE SET
  title = EXCLUDED.title,
  url = EXCLUDED.url,
  category_level = EXCLUDED.category_level,
  parent_slug = EXCLUDED.parent_slug;
