import type { PlatformConstants, PlatformScoringConfig } from "../platform-module.js";

/** Seed categories for the Zoom App Marketplace.
 *  These are the 48 selectable categories from GET /api/v1/app_categories */
export const ZOOM_SEED_CATEGORIES = [
  "analytics",
  "archiving",
  "broadcasting-streaming",
  "business-system-integrator",
  "crm",
  "carrier",
  "carrier-provider-exchange",
  "team-collaborations",
  "consumer",
  "customer-service",
  "eCommerce",
  "education",
  "engineering",
  "enterprise",
  "eventmanagement",
  "finance",
  "financialServices",
  "games",
  "government",
  "health-wellness",
  "health-care",
  "human-resources",
  "learning-development",
  "lifestyle",
  "marketing",
  "monitoring",
  "note-taking",
  "other",
  "peopleops",
  "presentations",
  "product",
  "productivity",
  "professor",
  "project-management",
  "recording-transcriptions",
  "sales-automation",
  "scheduling-calendar",
  "content-and-compliance",
  "smallBusiness",
  "social-activities",
  "student",
  "surveys-polls",
  "telehealth",
  "transcription-translation",
  "transcription",
  "virtual-backgrounds-scenes",
  "whiteboards",
  "workflow-automation",
] as const;

/** Display names for Zoom categories (slug → human-readable title).
 *  Source: GET /api/v1/app_categories */
export const ZOOM_CATEGORY_NAMES: Record<string, string> = {
  "zoom-apps": "Zoom Apps",
  "analytics": "Analytics",
  "archiving": "Archiving",
  "broadcasting-streaming": "Broadcasting & Streaming",
  "business-system-integrator": "Business System Integrator",
  "crm": "CRM",
  "carrier": "Carrier",
  "carrier-provider-exchange": "Carrier Provider Exchange",
  "team-collaborations": "Collaboration",
  "consumer": "Consumer",
  "customer-service": "Customer Service",
  "eCommerce": "E-Commerce",
  "education": "Education",
  "engineering": "Engineering",
  "enterprise": "Enterprise",
  "eventmanagement": "Event Management",
  "finance": "Finance",
  "financialServices": "Financial Services",
  "games": "Games",
  "government": "Government",
  "health-wellness": "Health & Wellness",
  "health-care": "Healthcare",
  "human-resources": "Human Resources",
  "learning-development": "Learning & Development",
  "lifestyle": "Lifestyle",
  "marketing": "Marketing",
  "monitoring": "Monitoring",
  "note-taking": "Note Taking",
  "other": "Other",
  "peopleops": "PeopleOps",
  "presentations": "Presentations",
  "product": "Product",
  "productivity": "Productivity",
  "professor": "Professor",
  "project-management": "Project Management",
  "recording-transcriptions": "Recordings",
  "sales-automation": "Sales",
  "scheduling-calendar": "Scheduling",
  "content-and-compliance": "Security & Compliance",
  "smallBusiness": "Small Business",
  "social-activities": "Social Activities",
  "student": "Student",
  "surveys-polls": "Surveys & Polls",
  "telehealth": "Telehealth",
  "transcription-translation": "Transcription & Translation",
  "transcription": "Transcriptions",
  "virtualbackground": "Virtual Background",
  "virtual-backgrounds-scenes": "Virtual Backgrounds & Scenes",
  "whiteboards": "Whiteboards",
  "workflow-automation": "Workflow Automation",
};

export const ZOOM_CONSTANTS: PlatformConstants = {
  seedCategories: [...ZOOM_SEED_CATEGORIES],
  maxCategoryDepth: 0,               // Flat categories
  defaultPagesPerCategory: 50,       // API pagination: up to 100 apps per page
  trackedFields: [
    "description",
    "companyName",
    "worksWith",
    "usage",
    "fedRampAuthorized",
    "essentialApp",
    "ratingStatistics",
    "categories",
  ],
  rateLimit: { minDelayMs: 300, maxDelayMs: 800 },
};

export const ZOOM_SCORING: PlatformScoringConfig = {
  pageSize: 100,
  pageDecay: 0.85,
  similarityWeights: {
    category: 0.35,
    feature: 0.0,
    keyword: 0.30,
    text: 0.35,
  },
  stopWords: new Set([
    "zoom", "meeting", "meetings", "webinar", "video", "marketplace",
    "app", "apps", "cloud",
    "the", "and", "for", "your", "our",
  ]),
};

/** Curated/featured section configs.
 *  These are fetched from a single API call to /api/v1/curatedCategory/preview/excludeBanner
 *  and keyed by their seoId. */
export const ZOOM_FEATURED_SECTIONS = [
  { seoId: "document-collaboration", sectionHandle: "_collection_document_collaboration", sectionTitle: "Document Collaboration" },
  { seoId: "apps-for-zoom-events", sectionHandle: "_collection_apps_for_zoom_events", sectionTitle: "Apps for Zoom Events" },
  { seoId: "apps-built-by-zoom", sectionHandle: "_collection_apps_built_by_zoom", sectionTitle: "Apps built by Zoom" },
  { seoId: "employee-engagement", sectionHandle: "_collection_employee_engagement", sectionTitle: "Employee Engagement" },
  { seoId: "apps-for-zoom-rooms", sectionHandle: "_collection_apps_for_zoom_rooms", sectionTitle: "Apps for Zoom Rooms" },
  { seoId: "new", sectionHandle: "_collection_new", sectionTitle: "New" },
  { seoId: "sales-and-marketing", sectionHandle: "_collection_sales_and_marketing", sectionTitle: "Sales & Marketing" },
  { seoId: "communications-and-scheduling", sectionHandle: "_collection_communications_and_scheduling", sectionTitle: "Communications & Scheduling" },
  { seoId: "microsoft-apps", sectionHandle: "_collection_microsoft_apps", sectionTitle: "Microsoft Apps" },
] as const;
