/**
 * Refresh Canva Cloudflare cookies for live search API.
 *
 * Launches a headless browser, navigates to canva.com/apps to pass
 * Cloudflare challenge, extracts fresh cookies, and writes them to
 * canva-search-config.json.
 *
 * Usage: cd apps/scraper && npx tsx scripts/canva-refresh-cookies.ts
 *
 * The __cf_bm cookie expires in ~30 minutes. Run this periodically
 * or before live search sessions.
 */
import { chromium } from "playwright";
import * as fs from "fs";
import * as path from "path";

const CONFIG_PATH = path.resolve(import.meta.dirname, "../canva-search-config.json");
const AUTH_STATE_CANDIDATES = [
  path.resolve(import.meta.dirname, "../canva-auth-state.json"),
  path.resolve(process.cwd(), "canva-auth-state.json"),
];

async function main() {
  console.log("Launching browser to refresh Canva cookies...");

  // Load existing auth state for cf_clearance (lasts ~1 year)
  let storageState: any;
  for (const p of AUTH_STATE_CANDIDATES) {
    if (fs.existsSync(p)) {
      storageState = JSON.parse(fs.readFileSync(p, "utf-8"));
      console.log(`  Auth state loaded from: ${p}`);
      break;
    }
  }

  const browser = await chromium.launch({
    headless: true,
    args: ["--disable-blink-features=AutomationControlled", "--no-sandbox"],
    ignoreDefaultArgs: ["--enable-automation"],
  });

  const context = await browser.newContext({
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
    ...(storageState && { storageState }),
  });

  const page = await context.newPage();

  console.log("  Navigating to canva.com/apps...");
  await page.goto("https://www.canva.com/apps", {
    waitUntil: "domcontentloaded",
    timeout: 30_000,
  });
  await page.waitForTimeout(5000);

  // Extract cookies
  const cookies = await context.cookies("https://www.canva.com");
  const cookieString = cookies
    .map((c) => `${c.name}=${c.value}`)
    .join("; ");

  console.log(`  Extracted ${cookies.length} cookies`);

  // Check for critical cookies
  const cfBm = cookies.find((c) => c.name === "__cf_bm");
  const cfClearance = cookies.find((c) => c.name === "cf_clearance");
  console.log(`  __cf_bm: ${cfBm ? "present" : "MISSING"}`);
  console.log(`  cf_clearance: ${cfClearance ? "present" : "MISSING"}`);

  if (!cfBm || !cfClearance) {
    console.error("  Critical Cloudflare cookies missing! Cloudflare may have blocked us.");
    await browser.close();
    process.exit(1);
  }

  // Write config — anonymous mode (no Canva auth needed)
  const config = {
    _comment: "Auto-generated by canva-refresh-cookies.ts. __cf_bm expires in ~30 min.",
    _refreshedAt: new Date().toISOString(),
    cookies: cookieString,
    headers: {
      "x-canva-user": "UAAAAAAAAAA",
      "x-canva-brand": "BAAAAAAAAAA",
      "x-canva-app": "apps_directory",
      "x-canva-locale": "en",
    },
    requestBody: {
      A: "UAAAAAAAAAA",
      B: "BAAAAAAAAAA",
      D: { D: true },
      G: 100,
    },
  };

  fs.writeFileSync(CONFIG_PATH, JSON.stringify(config, null, 2));
  console.log(`\n  Config written to: ${CONFIG_PATH}`);

  // Also save auth state for next time (preserves cf_clearance)
  const authState = await context.storageState();
  const authPath = AUTH_STATE_CANDIDATES[0];
  fs.writeFileSync(authPath, JSON.stringify(authState, null, 2));
  console.log(`  Auth state saved to: ${authPath}`);

  await browser.close();
  console.log("\nDone! Cookies are fresh for ~30 minutes.");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
