import type { PlatformId } from "@appranks/shared";

export interface MarketplaceEntry {
  name: string;
  platformId?: PlatformId;
}

/**
 * ~96 known app marketplaces.
 * platformId is set for the 11 platforms we already support.
 * Sorted alphabetically.
 */
export const MARKETPLACE_LIST: MarketplaceEntry[] = [
  { name: "Adobe Exchange" },
  { name: "Airtable Marketplace" },
  { name: "Asana App Directory" },
  { name: "Atlassian Marketplace", platformId: "atlassian" },
  { name: "AWS Marketplace" },
  { name: "BigCommerce Apps" },
  { name: "Bitrix24 Market" },
  { name: "Box App Center" },
  { name: "Bubble Plugin Marketplace" },
  { name: "Canva Apps", platformId: "canva" },
  { name: "Cisco Webex App Hub" },
  { name: "Claris Marketplace" },
  { name: "ClickUp Integrations" },
  { name: "Cloudflare Apps" },
  { name: "Confluence Marketplace" },
  { name: "Constant Contact Marketplace" },
  { name: "Copper Integrations" },
  { name: "Datadog Marketplace" },
  { name: "Discord App Directory" },
  { name: "DocuSign Apps" },
  { name: "Drift Integrations" },
  { name: "Drupal Marketplace" },
  { name: "eBay Apps Center" },
  { name: "Ecwid App Market" },
  { name: "Elastic Integrations" },
  { name: "Envato Market" },
  { name: "Figma Community" },
  { name: "Freshworks Marketplace" },
  { name: "Genesys AppFoundry" },
  { name: "GitHub Marketplace" },
  { name: "GitLab Integrations" },
  { name: "Google Cloud Marketplace" },
  { name: "Google Workspace Marketplace", platformId: "google_workspace" },
  { name: "Grafana Plugins" },
  { name: "Grammarly for Developers" },
  { name: "Hootsuite App Directory" },
  { name: "HubSpot App Marketplace", platformId: "hubspot" },
  { name: "Insightly AppConnect" },
  { name: "Intercom App Store" },
  { name: "Intuit App Store" },
  { name: "Jira Marketplace" },
  { name: "Keap Marketplace" },
  { name: "Klaviyo Integrations" },
  { name: "Lightspeed App Store" },
  { name: "Linear Integrations" },
  { name: "Magento Marketplace" },
  { name: "Mailchimp Integrations" },
  { name: "Marketo LaunchPoint" },
  { name: "Microsoft AppSource" },
  { name: "Microsoft Teams Apps" },
  { name: "Miro Marketplace" },
  { name: "Monday.com Apps" },
  { name: "Netsuite SuiteApp Marketplace" },
  { name: "Notion Integrations" },
  { name: "Okta Integration Network" },
  { name: "OneSignal Integrations" },
  { name: "Oracle Cloud Marketplace" },
  { name: "Outreach Integrations" },
  { name: "PagerDuty Integrations" },
  { name: "Pardot AppExchange" },
  { name: "Pipedrive Marketplace" },
  { name: "PrestaShop Addons" },
  { name: "QuickBooks App Store" },
  { name: "RingCentral App Gallery" },
  { name: "Salesforce AppExchange", platformId: "salesforce" },
  { name: "SAP Store" },
  { name: "SendGrid Integrations" },
  { name: "ServiceNow Store" },
  { name: "Shopify App Store", platformId: "shopify" },
  { name: "Slack App Directory" },
  { name: "Smartsheet Marketplace" },
  { name: "Splunk Apps" },
  { name: "Squarespace Extensions" },
  { name: "Stripe App Marketplace" },
  { name: "SugarCRM Marketplace" },
  { name: "Tableau Exchange" },
  { name: "Trello Power-Ups" },
  { name: "Twilio Integrations" },
  { name: "Typeform Integrations" },
  { name: "Webflow Apps" },
  { name: "Weebly App Center" },
  { name: "Wix App Market", platformId: "wix" },
  { name: "WooCommerce Marketplace" },
  { name: "WordPress Plugin Directory", platformId: "wordpress" },
  { name: "Workato Connector" },
  { name: "Workday Marketplace" },
  { name: "Xero App Store" },
  { name: "Zapier Integrations" },
  { name: "Zendesk Marketplace", platformId: "zendesk" },
  { name: "Zoho Marketplace", platformId: "zoho" },
  { name: "Zoom App Marketplace", platformId: "zoom" },
];
